version = 1

exclude_patterns = [
  "dist/**",
  "2025",
  ".astro/**",
  "src/assets/js/**"
]

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["vue"]
  environment = ["nodejs"]